from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
MIGRATION = ROOT / "supabase" / "migrations" / "0077_pcp_mp_cost_layers_single_output.sql"
ACTIONS = ROOT / "apps" / "web" / "app" / "pcp" / "actions.ts"
EDITOR = ROOT / "apps" / "web" / "app" / "pcp" / "production-editors.tsx"
MANUAL = ROOT / "docs" / "manuais" / "producao" / "FORMULAS_GARANTIAS.md"


class PcpCostLayersContractTests(unittest.TestCase):
    def test_mp_outgoing_movements_consume_entry_price_layers(self) -> None:
        sql = MIGRATION.read_text(encoding="utf-8")
        self.assertIn("est_movimentos_mp_custo_alocacoes", sql)
        self.assertIn("order by entry.created_at, entry.id, value.id", sql)
        self.assertIn("pg_advisory_xact_lock", sql)
        self.assertIn("movimento_valor_id", sql)

    def test_physical_layers_are_separate_from_currency_components(self) -> None:
        sql = MIGRATION.read_text(encoding="utf-8")
        self.assertIn("est_lotes_pi_custo_componentes", sql)
        self.assertIn("est_lotes_pa_custo_componentes", sql)
        self.assertIn("constraint est_pi_custo_lote_key unique (lote_pi_id)", sql)
        self.assertIn("constraint est_pa_custo_lote_key unique (lote_pa_id)", sql)
        self.assertNotIn("est_pi_custo_lote_moeda_key", sql)
        self.assertNotIn("est_pa_custo_lote_moeda_key", sql)

    def test_production_op_has_exactly_one_pi_output(self) -> None:
        sql = MIGRATION.read_text(encoding="utf-8")
        actions = ACTIONS.read_text(encoding="utf-8")
        editor = EDITOR.read_text(encoding="utf-8")
        self.assertIn("jsonb_array_length(p_outputs_jsonb) <> 1", sql)
        self.assertIn("production OP generates PI; PA must be generated by packaging order", sql)
        self.assertIn("outputs.length !== 1", actions)
        self.assertIn('<input type="hidden" name={`output_${index}_tipo`} value="PI" />', editor)
        self.assertNotIn('<option value="PA">Produto acabado</option>', editor.split("export function OutputRows", 1)[1])

    def test_process_and_stock_losses_are_distinct(self) -> None:
        sql = MIGRATION.read_text(encoding="utf-8")
        self.assertIn("pcp_op_perdas_processo", sql)
        self.assertIn("est_perdas_mp_custos_atuais", sql)
        self.assertIn("est_perdas_pi_custos_atuais", sql)
        self.assertIn("est_perdas_pa_custos_atuais", sql)

    def test_pa_cost_is_pi_plus_packaging_and_excludes_overhead(self) -> None:
        sql = MIGRATION.read_text(encoding="utf-8")
        manual = MANUAL.read_text(encoding="utf-8")
        self.assertIn("materialize_pcp_envase_pa_cost", sql)
        self.assertIn("est_movimentos_pi_custo_alocacoes", sql)
        self.assertIn("est_movimentos_mp_custo_alocacoes", sql)
        self.assertIn("custos operacionais e indiretos", manual.lower())
        self.assertIn("custo final do PA por embalagem", manual)


if __name__ == "__main__":
    unittest.main()
