import "server-only";
import { auditedRpc } from "@/lib/supabase/rpc";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { XLSX_MIME_TYPE, buildXlsxBytes, bytesToArrayBuffer, type XlsxRow } from "@/lib/tabular-export";
export type ApprovedPricingSnapshot={calculo_id:number;snapshot_json:Record<string,unknown>;result_sha256:string;decision:"APPROVED";approved_by:string;approved_at:string};
export async function getApprovedPricingSnapshot(id:number){const supabase=await createSupabaseServerClient();return auditedRpc<ApprovedPricingSnapshot>(supabase,"consultar_prc_snapshot_aprovado",{p_calculo_id:id},{origin:"apps/web/app/custos-precos/export",metadata:{action_key:"precificacao.view",axis:"own_any",domain:"precificacao",entity:"prc_calculos",entity_id:String(id)}});}
export function exportFilename(id:number,ext:"xlsx"|"pdf"){return `prc-calculo-${id}.${ext}`;}
export async function buildApprovedPricingXlsx(result:ApprovedPricingSnapshot){const s=assertSnapshot(result),c=objectArray(s.components),t=objectArray(objectValue(s.outputs)?.terms);if(c.length!==11||t.length!==18)throw new Error("Snapshot PRC incompleto para exportacao");const rows:XlsxRow[]=[...c.map(x=>({tipo:"Componente",campo:stringValue(x.field),origem:sourceLabel(x),valor:stringValue(x.value),prazo_dias:null,preco:null})),...t.map(x=>({tipo:"Preco comercial",campo:Number(x.prazo_dias)===0?"A vista":`${x.prazo_dias} dias`,origem:"Snapshot aprovado",valor:null,prazo_dias:numberValue(x.prazo_dias),preco:stringValue(x.preco)}))];return bytesToArrayBuffer(await buildXlsxBytes({title:"Formacao de custos e precos - snapshot aprovado",sheetName:"Snapshot aprovado",metadata:[{label:"Calculo",value:String(result.calculo_id)},{label:"Cenario",value:String(objectValue(s.scenario)?.name??"")},{label:"Politica",value:String(objectValue(s.policy)?.version??"")},{label:"Decisao",value:result.decision},{label:"SHA-256",value:result.result_sha256}],columns:[{key:"tipo",header:"Tipo",width:20},{key:"campo",header:"Produto / componente / prazo",width:30},{key:"origem",header:"Origem",width:28},{key:"valor",header:"Valor",width:22},{key:"prazo_dias",header:"Prazo (dias)",width:16,format:"integer"},{key:"preco",header:"Preco",width:22}],rows}));}
export function buildApprovedPricingPdf(result:ApprovedPricingSnapshot){const s=assertSnapshot(result),c=objectArray(s.components),t=objectArray(objectValue(s.outputs)?.terms);if(c.length!==11||t.length!==18)throw new Error("Snapshot PRC incompleto para exportacao");const lines=["FORMACAO DE CUSTOS E PRECOS","SNAPSHOT APROVADO",`Calculo: ${result.calculo_id}`,`Cenario: ${String(objectValue(s.scenario)?.name??"")}`,`Politica: ${String(objectValue(s.policy)?.version??"")}`,`Decisao: ${result.decision}`,`SHA-256: ${result.result_sha256}`,"","COMPONENTES E ORIGENS",...c.map(x=>`${stringValue(x.field)} | ${stringValue(x.value)} | ${sourceLabel(x)}`),"","PRECOS COMERCIAIS",...t.map(x=>`${Number(x.prazo_dias)===0?"A vista":`${x.prazo_dias} dias`} | ${stringValue(x.preco)}`)];const content=["BT","/F1 9 Tf","45 760 Td",...lines.flatMap((line,i)=>[i?"0 -13 Td":"",`(${pdfEscape(line)}) Tj`]),"ET"].filter(Boolean).join("\n");const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;offsets.slice(1).forEach(o=>{pdf+=`${String(o).padStart(10,"0")} 00000 n \n`;});return new TextEncoder().encode(pdf+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`).buffer;}
export { XLSX_MIME_TYPE };
function assertSnapshot(r:ApprovedPricingSnapshot){if(r.decision!=="APPROVED"||!r.snapshot_json||!r.result_sha256)throw new Error("Snapshot PRC nao aprovado");return r.snapshot_json;}
function objectValue(v:unknown):Record<string,unknown>|null{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:null;}
function objectArray(v:unknown){return Array.isArray(v)?v.map(objectValue).filter((x):x is Record<string,unknown>=>x!==null):[];}
function stringValue(v:unknown){return v==null?"":String(v);} function numberValue(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null;} function sourceLabel(c:Record<string,unknown>){const i=objectValue(c.input);return String(c.source_kind??i?.kind??"");} function pdfEscape(v:string){return v.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)").replace(/[^\x20-\x7e]/g,"?");}
