import "server-only";
import { auditedRpc } from "@/lib/supabase/rpc";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { XLSX_MIME_TYPE, buildXlsxBytes, bytesToArrayBuffer, type XlsxRow } from "@/lib/tabular-export";
export type ApprovedPricingSnapshot={calculo_id:number;snapshot_json:Record<string,unknown>;result_sha256:string;decision:"APPROVED";approved_by:string;approved_at:string};
export async function getApprovedPricingSnapshot(id:number){const supabase=await createSupabaseServerClient();return auditedRpc<ApprovedPricingSnapshot>(supabase,"consultar_prc_snapshot_aprovado",{p_calculo_id:id},{origin:"apps/web/app/custos-precos/export",metadata:{action_key:"precificacao.view",axis:"own_any",domain:"precificacao",entity:"prc_calculos",entity_id:String(id)}});}
export function exportFilename(id:number,ext:"xlsx"|"pdf"){return `prc-calculo-${id}.${ext}`;}
export async function buildApprovedPricingXlsx(result:ApprovedPricingSnapshot){const s=assertSnapshot(result),c=objectArray(s.components),t=objectArray(objectValue(s.outputs)?.terms);if(c.length!==11||t.length!==18)throw new Error("Snapshot PRC incompleto para exportacao");const f=objectValue(s.formula),o=objectValue(s.outputs),rows:XlsxRow[]=[...c.map(x=>{const i=objectValue(x.input);return {tipo:"Componente",campo:stringValue(x.field),unidade:stringValue(x.unidade),source_kind:sourceLabel(x),source_reference:stringValue(i?.reference),source_effective_date:stringValue(i?.effective_date),reason:stringValue(i?.reason),actor_id:stringValue(i?.actor_id),created_at:stringValue(i?.created_at),valor:stringValue(x.value),prazo_dias:null,preco:null};}),...t.map(x=>({tipo:"Preco comercial",campo:Number(x.prazo_dias)===0?"A vista":`${x.prazo_dias} dias`,unidade:"",source_kind:"Snapshot aprovado",source_reference:"",source_effective_date:"",reason:"",actor_id:"",created_at:"",valor:null,prazo_dias:numberValue(x.prazo_dias),preco:stringValue(x.preco)}))];return bytesToArrayBuffer(await buildXlsxBytes({title:"Formacao de custos e precos - snapshot aprovado",sheetName:"Snapshot aprovado",metadata:exportMetadata(result,s,f,o),columns:[{key:"tipo",header:"Tipo",width:20},{key:"campo",header:"Campo / prazo",width:30},{key:"unidade",header:"Unidade",width:14},{key:"source_kind",header:"Tipo de origem",width:22},{key:"source_reference",header:"Referencia da origem",width:28},{key:"source_effective_date",header:"Data efetiva da origem",width:22},{key:"reason",header:"Motivo",width:30},{key:"actor_id",header:"Ator",width:38},{key:"created_at",header:"Criado em",width:24},{key:"valor",header:"Valor",width:22},{key:"prazo_dias",header:"Prazo (dias)",width:16,format:"integer"},{key:"preco",header:"Preco",width:22}],rows}));}
export function buildApprovedPricingPdf(result:ApprovedPricingSnapshot){const s=assertSnapshot(result),c=objectArray(s.components),t=objectArray(objectValue(s.outputs)?.terms);if(c.length!==11||t.length!==18)throw new Error("Snapshot PRC incompleto para exportacao");const f=objectValue(s.formula),o=objectValue(s.outputs),lines=["FORMACAO DE CUSTOS E PRECOS","SNAPSHOT APROVADO",...exportMetadata(result,s,f,o).map(x=>`${x.label}: ${x.value}`),"","MEMORIA DA FORMULA",`Versao: ${stringValue(f?.version)}`,`Custo base exato: ${stringValue(f?.cost_base_exact)}`,`Denominador exato: ${stringValue(f?.denominator_exact)}`,`Preco a vista exato: ${stringValue(f?.cash_price_exact)}`,`CMV percentual: ${stringValue(f?.cmv_percent_exact)}`,`Contribuicao liquida: ${stringValue(f?.net_contribution_exact)}`,"","COMPONENTES E PROVENIENCIA",...c.map(x=>{const i=objectValue(x.input);return `${stringValue(x.field)} | ${stringValue(x.value)} | ${stringValue(x.unidade)} | ${sourceLabel(x)} | ${stringValue(i?.reference)} | ${stringValue(i?.effective_date)} | ${stringValue(i?.reason)} | ${stringValue(i?.actor_id)} | ${stringValue(i?.created_at)}`;}),"","PRECOS COMERCIAIS",`Preco a vista: ${stringValue(o?.cash_price)}`,...t.map(x=>`${Number(x.prazo_dias)===0?"A vista":`${x.prazo_dias} dias`} | ${stringValue(x.preco)}`)];const content=["BT","/F1 7 Tf","45 800 Td",...lines.flatMap((line,i)=>[i?"0 -10 Td":"",`(${pdfEscape(line)}) Tj`]),"ET"].filter(Boolean).join("\n");const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;offsets.slice(1).forEach(o=>{pdf+=`${String(o).padStart(10,"0")} 00000 n \n`;});return new TextEncoder().encode(pdf+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`).buffer;}
export { XLSX_MIME_TYPE };
function assertSnapshot(r:ApprovedPricingSnapshot){if(r.decision!=="APPROVED"||!r.snapshot_json||!r.result_sha256)throw new Error("Snapshot PRC nao aprovado");return r.snapshot_json;}
function objectValue(v:unknown):Record<string,unknown>|null{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:null;}
function objectArray(v:unknown){return Array.isArray(v)?v.map(objectValue).filter((x):x is Record<string,unknown>=>x!==null):[];}
function stringValue(v:unknown){return v==null?"":String(v);} function numberValue(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null;} function sourceLabel(c:Record<string,unknown>){return String(c.source_kind??objectValue(c.input)?.kind??"");} function exportMetadata(result:ApprovedPricingSnapshot,s:Record<string,unknown>,f:Record<string,unknown>|null,o:Record<string,unknown>|null){return [{label:"Calculo",value:String(result.calculo_id)},{label:"Cenario",value:String(objectValue(s.scenario)?.name??"")},{label:"Politica",value:String(objectValue(s.policy)?.version??"")},{label:"Decisao",value:result.decision},{label:"Aprovado por",value:result.approved_by},{label:"Aprovado em",value:result.approved_at},{label:"SHA-256",value:result.result_sha256},{label:"Formula",value:String(f?.version??"")},{label:"Custo base exato",value:String(f?.cost_base_exact??"")},{label:"Denominador exato",value:String(f?.denominator_exact??"")},{label:"Preco a vista exato",value:String(f?.cash_price_exact??o?.cash_price_exact??"")},{label:"Preco a vista comercial",value:String(o?.cash_price??"")},{label:"CMV percentual",value:String(f?.cmv_percent_exact??"")},{label:"Contribuicao liquida",value:String(f?.net_contribution_exact??"")}];} function pdfEscape(v:string){return v.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)").replace(/[^\x20-\x7e]/g,"?");}
