import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";

import { calculatePricingScenarioAction, createPricingPolicyAction, createPricingScenarioAction, reviewPricingCalculationAction, reviewPricingPolicyAction } from "./actions";
import { getPricingAccess, getPricingWorkspace } from "@/lib/cost-pricing";
import styles from "./pricing.module.css";

type Params=Record<string,string|string[]|undefined>;
const COSTS=[
  ["materia_prima","Materia-prima","R$/L"],["embalagem","Embalagem","R$/L"],["custo_pontuacao_vendedor","Pontuacao do vendedor","R$/L"],
  ["custo_pontuacao_revenda","Pontuacao da revenda","R$/L"],["premiacao_revenda","Premiacao da revenda","R$/L"],["premio_producao","Premio de producao","R$/L"],["frete","Frete","R$/L"],
  ["comissao","Comissao","fracao"],["risco","Risco","fracao"],["marketing","Marketing","fracao"],["tributacao","Tributacao","fracao"],
] as const;

export default async function CostPricingPage({searchParams}:{searchParams?:Promise<Params>}){
  const params=searchParams?await searchParams:{}; const access=await getPricingAccess();
  if(!access.view)redirect("/modulo-indisponivel?module=precificacao&reason=permission");
  const workspace=await getPricingWorkspace(); const data=workspace.data; const result=single(params.result);
  const approvedVersions=(data?.politicas.flatMap((p)=>p.versoes.map((v)=>({...v,policy:p}))).filter((v)=>v.status==="APPROVED")??[]);
  return <main className={styles.workspace}>
    <header className={styles.heading}><div><span className="eyebrow">Precificacao</span><h1>Formacao de custos e precos</h1><p>Construa cenarios auditaveis sem alterar custos reais, estoque ou listas comerciais.</p></div><span className="status-chip">Fundacao ISO</span></header>
    {result?<Notice result={result}/>:null}{workspace.error?<div className="notice-panel warning"><strong>Consulta indisponivel</strong><span>{workspace.error}</span></div>:null}
    <section className={styles.summary} aria-label="Etapa atual"><div><span>Politicas</span><strong>{data?.politicas.length??0}</strong></div><div><span>Cenarios</span><strong>{data?.cenarios.length??0}</strong></div><div><span>Calculos</span><strong>{data?.cenarios.reduce((n,s)=>n+s.calculos.length,0)??0}</strong></div><div><span>Publicacao comercial</span><strong>Fora desta etapa</strong></div></section>

    <nav className={styles.tabs} aria-label="Areas da formacao"><a href="#custos">Custos e referencias</a><a href="#cenarios">Cenarios</a><a href="#memoria">Memoria de calculo</a><a href="#revisao">Revisao e aprovacao</a><a href="#dossie">Dossie</a></nav>

    <section className={styles.band} id="custos"><div className={styles.sectionHeading}><div><h2>Custos e referencias</h2><p>A politica define o metodo e o arredondamento. Cada cenario congela a origem de todos os componentes.</p></div><span>Proximo responsavel: gestor de precificacao</span></div>
      {access.policy?<form action={createPricingPolicyAction} className={styles.form}><input type="hidden" name="idempotency_key" value={randomUUID()}/><label>Codigo<input name="codigo" placeholder="POL-MARGEM-01" required/></label><label className={styles.wide}>Nome<input name="nome" placeholder="Politica comercial padrao" required/></label><label>Metodo<select name="metodo" defaultValue="margem_liquida"><option value="margem_liquida">Margem liquida</option><option value="markup">Markup</option></select></label><label>Lucro minimo<input name="lucro_minimo" inputMode="decimal" placeholder="0,15"/></label><label>Markup<input name="markup" inputMode="decimal" placeholder="0,25"/></label><label>Juros mensais<input name="juros_mensais" inputMode="decimal" placeholder="0,02" required/></label><label className={styles.wide}>Motivo<input name="motivo" minLength={10} required placeholder="Explique a finalidade desta versao"/></label><button className="primary-button">Criar versao</button></form>:<Permission/>}
    </section>

    <section className={styles.band} id="cenarios"><div className={styles.sectionHeading}><div><h2>Cenarios</h2><p>Substituicoes manuais afetam somente o novo cenario e nunca sobrescrevem custo, formula ou estoque.</p></div><span>11 componentes obrigatorios</span></div>
      {access.scenario?<form action={createPricingScenarioAction} className={styles.form}><input type="hidden" name="idempotency_key" value={randomUUID()}/><label className={styles.wide}>Politica aprovada<select name="politica_versao_id" required defaultValue=""><option value="">Selecione</option>{approvedVersions.map((v)=><option key={v.id} value={v.id}>{v.policy.codigo} - versao {v.versao}</option>)}</select></label><label className={styles.wide}>Produto e apresentacao<select name="produto_embalagem_id" required defaultValue=""><option value="">Selecione</option>{data?.apresentacoes.map((p)=><option key={p.id} value={p.id}>{p.codigo} - {p.produto} / {p.apresentacao}</option>)}</select></label><label className={styles.wide}>Nome do cenario<input name="nome" required placeholder="Cenario base para homologacao"/></label><label className={styles.wide}>Motivo<input name="motivo" minLength={10} required/></label><label>Origem<select name="source_kind" defaultValue="fixture_validacao"><option value="system">Sistema</option><option value="substituicao_manual">Substituicao manual</option><option value="fixture_validacao">Validacao sintetica</option></select></label><label>Referencia<input name="source_reference" required placeholder="SIMULACAO-001"/></label><label>Data da fonte<input name="source_effective_date" type="date" required/></label><label className={styles.wide}>Justificativa da fonte<input name="source_reason" minLength={10} required/></label><div className={styles.components}>{COSTS.map(([name,label,unit])=><label key={name}>{label}<span>{unit}</span><input name={name} inputMode="decimal" min="0" step="0.00000001" required/></label>)}</div><button className="primary-button">Congelar cenario</button></form>:<Permission/>}
    </section>

    <section className={styles.band} id="memoria"><div className={styles.sectionHeading}><div><h2>Memoria de calculo</h2><p>O banco calcula o preco a vista, CMV, contribuicao e os 18 prazos. Valores ausentes bloqueiam o calculo.</p></div></div>{data?.cenarios.length?<div className={styles.cards}>{data.cenarios.map((s)=><article key={s.id}><h3>{s.nome}</h3><p>{s.motivo}</p><span className="status-chip">{s.componentes.some((c)=>c.source_kind==="substituicao_manual")?"Possui substituicao manual":"Fontes congeladas"}</span>{access.calculate?<form action={calculatePricingScenarioAction}><input type="hidden" name="idempotency_key" value={randomUUID()}/><input type="hidden" name="cenario_id" value={s.id}/><label>Motivo do calculo<input name="motivo" minLength={10} required defaultValue="Calculo governado para revisao"/></label><button className="secondary-button">Calcular memoria</button></form>:null}</article>)}</div>:<Empty text="Nenhum cenario congelado."/>}</section>

    <section className={styles.band} id="revisao"><div className={styles.sectionHeading}><div><h2>Revisao e aprovacao</h2><p>Quem criou a politica, o cenario ou o calculo nao pode aprovar o proprio trabalho.</p></div><span>Segregacao obrigatoria</span></div><div className={styles.cards}>{data?.politicas.flatMap((p)=>p.versoes.filter((v)=>v.status==="PENDING").map((v)=><article key={`p-${v.id}`}><h3>{p.nome} - versao {v.versao}</h3><p>Metodo: {label(v.metodo)}</p>{access.policyReview?<ReviewForm id={v.id} kind="policy"/>:<Permission/>}</article>))}{data?.cenarios.flatMap((s)=>s.calculos.filter((c)=>c.status==="PENDING").map((c)=><article key={`c-${c.id}`}><h3>{s.nome}</h3><p>Preco a vista {money(c.preco_vista)}; calculo aguardando decisao.</p>{access.calculationReview?<ReviewForm id={c.id} kind="calculation"/>:<Permission/>}</article>))}</div></section>

    <section className={styles.band} id="dossie"><div className={styles.sectionHeading}><div><h2>Dossie</h2><p>Versoes, fontes, resultados e historico permanecem reproduziveis. O detalhe tecnico fica recolhido.</p></div></div>{data?.cenarios.flatMap((s)=>s.calculos.map((c)=><article className={styles.dossier} key={c.id}><div><h3>{s.nome}</h3><span className={`status-chip ${c.status==="APPROVED"?"ativo":""}`}>{status(c.status)}</span></div><dl><div><dt>Preco a vista</dt><dd>{money(c.preco_vista)}</dd></div><div><dt>CMV</dt><dd>{percent(c.cmv_percentual)}</dd></div><div><dt>Contribuicao liquida</dt><dd>{money(c.contribuicao_liquida)}</dd></div><div><dt>Versao do calculo</dt><dd>{c.id}</dd></div></dl><div className={styles.terms}>{c.prazos.map((t)=><span key={t.prazo_dias}><small>{t.prazo_dias} dias</small><strong>{money(t.preco)}</strong></span>)}</div><details><summary>Detalhe de auditoria</summary><p>Registro calculado em {dateTime(c.calculated_at)}. Identificador tecnico {c.result_sha256.slice(0,12)}.</p></details></article>))}</section>
  </main>;
}

function ReviewForm({id,kind}:{id:number;kind:"policy"|"calculation"}){const action=kind==="policy"?reviewPricingPolicyAction:reviewPricingCalculationAction;return <form action={action}><input type="hidden" name="idempotency_key" value={randomUUID()}/><input type="hidden" name={kind==="policy"?"versao_id":"calculo_id"} value={id}/><label>Decisao<select name="decisao"><option value="APPROVED">Aprovar</option><option value="REJECTED">Rejeitar</option></select></label><label>Justificativa<input name="justificativa" minLength={10} required/></label><button className="primary-button">Registrar decisao</button></form>}
function Permission(){return <div className="permission-state"><strong>Acao indisponivel</strong><span>Sua conta pode consultar, mas nao possui a alcada desta etapa.</span></div>}
function Empty({text}:{text:string}){return <div className="empty-state"><strong>Nenhum registro</strong><span>{text}</span></div>}
function Notice({result}:{result:string}){const errors=new Set(["permission","denominator","components","segregation","idempotency","failed","invalid-request"]);return <div className={`notice-panel ${errors.has(result)?"warning":"success"}`} role="status"><strong>{errors.has(result)?"Operacao nao concluida":"Registro concluido"}</strong><span>{message(result)}</span></div>}
function message(value:string){return ({permission:"Sua conta nao possui alcada para esta etapa.",denominator:"O conjunto de taxas torna o denominador invalido.",components:"Todos os componentes e suas fontes precisam estar resolvidos.",segregation:"A mesma pessoa nao pode criar e aprovar este fato.",idempotency:"A solicitacao foi reutilizada com conteudo diferente.","policy-saved":"Versao de politica criada e enviada para revisao.","policy-review-saved":"Decisao da politica registrada.","scenario-saved":"Cenario e fontes congelados.","calculation-saved":"Memoria de calculo registrada com 18 prazos.","calculation-review-saved":"Decisao do calculo registrada."} as Record<string,string>)[value]??"Nenhum fato parcial foi criado."}
function single(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}
function label(value:string){return value==="margem_liquida"?"Margem liquida":"Markup"}
function status(value:string){return value==="APPROVED"?"Aprovado":value==="REJECTED"?"Rejeitado":"Aguardando revisao"}
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:2}).format(value)}
function percent(value:number){return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(value)+"%"}
function dateTime(value:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value))}
