-- PRC-01 P1 hardening: source provenance, complete snapshots and concurrent idempotency.

create or replace function public.prc_lock_idempotency_key(p_key uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_key is null then raise exception 'chave de idempotencia e obrigatoria'; end if;
  perform pg_advisory_xact_lock(hashtextextended('prc-idempotency:'||p_key::text,0));
end $$;

create or replace function public.salvar_prc_politica_versao_idempotente(p_key uuid,p_codigo text,p_nome text,p_metodo text,p_lucro_minimo numeric,p_markup numeric,p_juros_mensais numeric,p_motivo text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_ctx jsonb; v_actor uuid; v_payload jsonb; v_existing bigint; v_policy public.prc_politicas%rowtype; v_version integer; v_doc jsonb; v_id bigint;
begin
  v_ctx:=public.begin_audited_rpc('precificacao.policy.manage','precificacao','prc_politica_versoes','change_type',jsonb_build_object('correlation_id',p_key::text)); v_actor:=public.current_actor_id(); v_payload:=jsonb_build_object('codigo',upper(btrim(p_codigo)),'nome',btrim(p_nome),'metodo',p_metodo,'lucro_minimo',p_lucro_minimo,'markup',p_markup,'juros_mensais',p_juros_mensais,'motivo',btrim(p_motivo)); perform public.prc_lock_idempotency_key(p_key); v_existing:=public.prc_idempotent_result(p_key,'policy',v_payload); if v_existing is not null then return v_existing; end if;
  if p_metodo not in ('margem_liquida','markup') or p_juros_mensais is null or p_juros_mensais<0 or length(btrim(coalesce(p_motivo,'')))<10 then raise exception 'politica invalida'; end if;
  select * into v_policy from public.prc_politicas where codigo=upper(btrim(p_codigo)); if not found then insert into public.prc_politicas(codigo,nome,created_by) values(upper(btrim(p_codigo)),btrim(p_nome),v_actor) returning * into v_policy; elsif v_policy.nome<>btrim(p_nome) then raise exception 'codigo de politica ja possui outro nome'; end if;
  perform pg_advisory_xact_lock(hashtextextended('prc-policy:'||v_policy.id::text,0)); select coalesce(max(versao),0)+1 into v_version from public.prc_politica_versoes where politica_id=v_policy.id;
  v_doc:=jsonb_build_object('schema','prc-policy-v1','politica_id',v_policy.id,'codigo',v_policy.codigo,'nome',v_policy.nome,'versao',v_version,'metodo',p_metodo,'lucro_minimo',p_lucro_minimo,'markup',p_markup,'juros_mensais',p_juros_mensais,'arredondamento','HALF_UP','casas_decimais',2);
  insert into public.prc_politica_versoes(politica_id,versao,metodo,lucro_minimo,markup,juros_mensais,documento_json,documento_sha256,motivo,created_by) values(v_policy.id,v_version,p_metodo,p_lucro_minimo,p_markup,p_juros_mensais,v_doc,public.prc_sha256(v_doc),btrim(p_motivo),v_actor) returning id into v_id;
  insert into public.prc_requisicoes values(p_key,'policy',v_actor,public.prc_sha256(v_payload),v_id,clock_timestamp()); perform public.log_audited_rpc_change('precificacao','prc_politica_versoes',v_id::text,'precificacao.politica_versao_criada','precificacao.policy.manage',v_ctx,null,v_doc,jsonb_build_object('motivo',btrim(p_motivo)),'database_rpc'); return v_id;
end $$;

create or replace function public.decidir_prc_politica_versao_idempotente(p_key uuid,p_versao_id bigint,p_decisao text,p_justificativa text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_ctx jsonb; v_actor uuid; v_payload jsonb; v_existing bigint; v_version public.prc_politica_versoes%rowtype; v_id bigint;
begin
  v_ctx:=public.begin_audited_rpc('precificacao.policy.review','precificacao','prc_politica_revisoes','status_transition',jsonb_build_object('correlation_id',p_key::text)); v_actor:=public.current_actor_id(); v_payload:=jsonb_build_object('versao_id',p_versao_id,'decisao',upper(p_decisao),'justificativa',btrim(p_justificativa)); perform public.prc_lock_idempotency_key(p_key); v_existing:=public.prc_idempotent_result(p_key,'policy_review',v_payload); if v_existing is not null then return v_existing; end if;
  select * into v_version from public.prc_politica_versoes where id=p_versao_id; if not found then raise exception 'versao de politica inexistente'; end if; if v_version.created_by=v_actor then raise exception 'criador nao pode aprovar ou rejeitar a propria politica'; end if; if upper(p_decisao) not in ('APPROVED','REJECTED') or length(btrim(coalesce(p_justificativa,'')))<10 then raise exception 'decisao de politica invalida'; end if;
  insert into public.prc_politica_revisoes(politica_versao_id,decisao,justificativa,actor_id) values(p_versao_id,upper(p_decisao),btrim(p_justificativa),v_actor) returning id into v_id; insert into public.prc_requisicoes values(p_key,'policy_review',v_actor,public.prc_sha256(v_payload),v_id,clock_timestamp()); perform public.log_audited_rpc_change('precificacao','prc_politica_revisoes',v_id::text,'precificacao.politica_revisada','precificacao.policy.review',v_ctx,null,jsonb_build_object('decisao',upper(p_decisao)),jsonb_build_object('politica_versao_id',p_versao_id,'justificativa',btrim(p_justificativa)),'database_rpc'); return v_id;
end $$;

create or replace function public.criar_prc_cenario_idempotente(p_key uuid,p_politica_versao_id bigint,p_produto_embalagem_id bigint,p_nome text,p_motivo text,p_componentes jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_ctx jsonb; v_actor uuid; v_payload jsonb; v_existing bigint; v_id bigint; v_item jsonb; v_count integer:=0; v_expected text[]:=array['materia_prima','embalagem','custo_pontuacao_vendedor','custo_pontuacao_revenda','premiacao_revenda','premio_producao','frete','comissao','risco','marketing','tributacao']; v_field text; v_unit text; v_source text;
begin
  v_ctx:=public.begin_audited_rpc('precificacao.scenario.manage','precificacao','prc_cenarios','field_risk',jsonb_build_object('correlation_id',p_key::text)); v_actor:=public.current_actor_id(); v_payload:=jsonb_build_object('politica_versao_id',p_politica_versao_id,'produto_embalagem_id',p_produto_embalagem_id,'nome',btrim(p_nome),'motivo',btrim(p_motivo),'componentes',p_componentes); perform public.prc_lock_idempotency_key(p_key); v_existing:=public.prc_idempotent_result(p_key,'scenario',v_payload); if v_existing is not null then return v_existing; end if;
  if not exists(select 1 from public.prc_politica_revisoes where politica_versao_id=p_politica_versao_id and decisao='APPROVED') then raise exception 'politica precisa estar aprovada'; end if; if not exists(select 1 from public.cad_produto_embalagens where id=p_produto_embalagem_id) then raise exception 'apresentacao inexistente'; end if; if jsonb_typeof(p_componentes)<>'array' or jsonb_array_length(p_componentes)<>11 or length(btrim(coalesce(p_motivo,'')))<10 then raise exception 'cenario exige os 11 componentes e motivo'; end if;
  insert into public.prc_cenarios(politica_versao_id,produto_embalagem_id,nome,motivo,correlation_id,created_by) values(p_politica_versao_id,p_produto_embalagem_id,btrim(p_nome),btrim(p_motivo),p_key::text,v_actor) returning id into v_id;
  for v_item in select value from jsonb_array_elements(p_componentes) loop v_field:=v_item->>'campo'; v_unit:=v_item->>'unidade'; v_source:=v_item->>'source_kind'; if not (v_field=any(v_expected)) or (v_item->>'valor') is null or (v_item->>'valor')::numeric<0 then raise exception 'componente invalido ou ausente'; end if; if (v_field=any(array['comissao','risco','marketing','tributacao']) and (v_unit<>'FRACAO' or (v_item->>'valor')::numeric>=1)) or (not (v_field=any(array['comissao','risco','marketing','tributacao'])) and v_unit<>'BRL_L') then raise exception 'unidade de componente incompativel'; end if; if v_source not in ('system','substituicao_manual','fixture_validacao') or length(btrim(coalesce(v_item->>'source_reference','')))<3 or nullif(v_item->>'source_effective_date','') is null or length(btrim(coalesce(v_item->>'reason','')))<10 then raise exception 'fonte de componente incompleta'; end if; if v_source='system' then raise exception 'fonte system sem adapter canonico'; end if; if v_source='fixture_validacao' and public.current_system_environment()<>'test' then raise exception 'fixture_validacao requer ambiente de teste'; end if; insert into public.prc_cenario_componentes(cenario_id,campo,valor,unidade,source_kind,source_reference,source_effective_date,reason,actor_id) values(v_id,v_field,(v_item->>'valor')::numeric,v_unit,v_source,btrim(v_item->>'source_reference'),(v_item->>'source_effective_date')::date,btrim(v_item->>'reason'),v_actor); v_count:=v_count+1; end loop;
  if v_count<>11 then raise exception 'cenario incompleto'; end if; insert into public.prc_requisicoes values(p_key,'scenario',v_actor,public.prc_sha256(v_payload),v_id,clock_timestamp()); perform public.log_audited_rpc_change('precificacao','prc_cenarios',v_id::text,'precificacao.cenario_criado','precificacao.scenario.manage',v_ctx,null,jsonb_build_object('politica_versao_id',p_politica_versao_id,'produto_embalagem_id',p_produto_embalagem_id,'componentes',v_count),jsonb_build_object('motivo',btrim(p_motivo)),'database_rpc'); return v_id;
end $$;

create or replace function public.calcular_prc_cenario_idempotente(p_key uuid,p_cenario_id bigint,p_motivo text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_ctx jsonb; v_actor uuid; v_payload jsonb; v_existing bigint; v_s public.prc_cenarios%rowtype; v_p public.prc_politica_versoes%rowtype; v_base numeric; v_comm numeric; v_tax numeric; v_marketing numeric; v_risk numeric; v_den numeric; v_cash_exact numeric; v_cash numeric; v_cmv numeric; v_contrib numeric; v_doc jsonb; v_hash text; v_calc_id bigint; v_exact numeric; v_component public.prc_cenario_componentes%rowtype; v_components jsonb; v_terms jsonb:='[]'::jsonb; v_now timestamptz; v_n integer;
begin
  v_ctx:=public.begin_audited_rpc('precificacao.calculate','precificacao','prc_calculos','field_risk',jsonb_build_object('correlation_id',p_key::text)); v_actor:=public.current_actor_id(); v_payload:=jsonb_build_object('cenario_id',p_cenario_id,'motivo',btrim(p_motivo)); perform public.prc_lock_idempotency_key(p_key); v_existing:=public.prc_idempotent_result(p_key,'calculation',v_payload); if v_existing is not null then return v_existing; end if;
  select * into v_s from public.prc_cenarios where id=p_cenario_id; if not found then raise exception 'cenario inexistente'; end if; select * into v_p from public.prc_politica_versoes where id=v_s.politica_versao_id; if not found or not exists(select 1 from public.prc_politica_revisoes where politica_versao_id=v_p.id and decisao='APPROVED') then raise exception 'politica aprovada ausente'; end if; if (select count(*) from public.prc_cenario_componentes where cenario_id=p_cenario_id)<>11 then raise exception 'componente ausente bloqueia calculo'; end if; if exists(select 1 from public.prc_cenario_componentes where cenario_id=p_cenario_id and source_kind='system') then raise exception 'fonte system sem provenance canonica'; end if;
  select sum(valor) filter(where campo in ('materia_prima','embalagem','custo_pontuacao_vendedor','custo_pontuacao_revenda','premiacao_revenda','premio_producao','frete')), max(valor) filter(where campo='comissao'),max(valor) filter(where campo='tributacao'),max(valor) filter(where campo='marketing'),max(valor) filter(where campo='risco') into v_base,v_comm,v_tax,v_marketing,v_risk from public.prc_cenario_componentes where cenario_id=p_cenario_id; if v_base is null or v_comm is null or v_tax is null or v_marketing is null or v_risk is null then raise exception 'fonte ausente bloqueia calculo'; end if; v_den:=1-v_comm-v_tax-v_marketing-case when v_p.metodo='margem_liquida' then v_p.lucro_minimo else 0 end; if v_den<=0 then raise exception 'denominador deve ser positivo'; end if; if v_p.metodo='margem_liquida' then v_cash_exact:=v_base/v_den; else v_cash_exact:=v_base*(1+v_p.markup)/(1-v_comm-v_tax-v_marketing); end if;
  v_cash:=round(v_cash_exact,2); v_cmv:=round(((select sum(valor) from public.prc_cenario_componentes where cenario_id=p_cenario_id and campo in ('materia_prima','embalagem'))/v_cash)*100,8); v_contrib:=round(v_cash-v_base-(v_cash*v_comm)-(v_cash*v_tax)-(v_cash*v_marketing),8); v_now:=clock_timestamp(); select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'campo',c.campo,'valor',c.valor::text,'unidade',c.unidade,'source_kind',c.source_kind,'input',jsonb_build_object('reference',c.source_reference,'effective_date',c.source_effective_date,'reason',c.reason,'actor_id',c.actor_id,'created_at',c.created_at)) order by c.campo),'[]'::jsonb) into v_components from public.prc_cenario_componentes c where c.cenario_id=p_cenario_id;
  for v_n in 1..18 loop v_exact:=v_cash + v_cash*(((1+v_p.juros_mensais)^v_n-1)+v_risk)/(1-v_comm-v_tax-v_marketing); v_terms:=v_terms||jsonb_build_array(jsonb_build_object('parcela_n',v_n,'prazo_dias',v_n*30,'preco_exato',v_exact::text,'preco',round(v_exact,2)::text)); end loop;
  v_doc:=jsonb_build_object('schema','prc-calculation-v2','calculation',jsonb_build_object('actor_id',v_actor,'calculated_at',v_now,'scenario_id',p_cenario_id),'policy',jsonb_build_object('version_id',v_p.id,'document_sha256',v_p.documento_sha256,'method',v_p.metodo,'minimum_margin',v_p.lucro_minimo,'markup',v_p.markup,'monthly_interest',v_p.juros_mensais,'rounding','HALF_UP','decimal_places',2),'scenario',jsonb_build_object('id',v_s.id,'product_packaging_id',v_s.produto_embalagem_id,'name',v_s.nome,'created_by',v_s.created_by,'created_at',v_s.created_at),'components',v_components,'formula',jsonb_build_object('version','prc-formula-v1','cost_base_exact',v_base::text,'denominator_exact',v_den::text,'cash_price_exact',v_cash_exact::text,'cmv_percent_exact',v_cmv::text,'net_contribution_exact',v_contrib::text),'outputs',jsonb_build_object('cash_price_exact',v_cash_exact::text,'cash_price',v_cash::text,'terms',v_terms)); v_hash:=public.prc_sha256(v_doc);
  insert into public.prc_calculos(cenario_id,politica_versao_id,politica_documento_sha256,metodo,custo_base_exato,preco_vista_exato,preco_vista,cmv_percentual,contribuicao_liquida,intermediarios_json,arredondamento,casas_decimais,motivo,correlation_id,result_sha256,created_by,calculated_at) values(p_cenario_id,v_p.id,v_p.documento_sha256,v_p.metodo,v_base,v_cash_exact,v_cash,v_cmv,v_contrib,v_doc,'HALF_UP',2,btrim(p_motivo),p_key::text,v_hash,v_actor,v_now) returning id into v_calc_id;
  for v_component in select * from public.prc_cenario_componentes where cenario_id=p_cenario_id order by campo loop insert into public.prc_calculo_componentes(calculo_id,cenario_componente_id,campo,valor,unidade,source_kind,source_reference,source_effective_date,reason) values(v_calc_id,v_component.id,v_component.campo,v_component.valor,v_component.unidade,v_component.source_kind,v_component.source_reference,v_component.source_effective_date,v_component.reason); end loop;
  for v_n in 1..18 loop v_exact:=v_cash + v_cash*(((1+v_p.juros_mensais)^v_n-1)+v_risk)/(1-v_comm-v_tax-v_marketing); insert into public.prc_calculo_precos_prazo(calculo_id,parcela_n,prazo_dias,preco_exato,preco) values(v_calc_id,v_n,v_n*30,v_exact,round(v_exact,2)); end loop;
  insert into public.prc_requisicoes values(p_key,'calculation',v_actor,public.prc_sha256(v_payload),v_calc_id,clock_timestamp()); perform public.log_audited_rpc_change('precificacao','prc_calculos',v_calc_id::text,'precificacao.calculo_registrado','precificacao.calculate',v_ctx,null,v_doc,jsonb_build_object('motivo',btrim(p_motivo),'result_sha256',v_hash),'database_rpc'); return v_calc_id;
end $$;

create or replace function public.decidir_prc_calculo_idempotente(p_key uuid,p_calculo_id bigint,p_decisao text,p_justificativa text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_ctx jsonb; v_actor uuid; v_payload jsonb; v_existing bigint; v_calc public.prc_calculos%rowtype; v_s public.prc_cenarios%rowtype; v_id bigint;
begin
  v_ctx:=public.begin_audited_rpc('precificacao.calculation.review','precificacao','prc_calculo_decisoes','status_transition',jsonb_build_object('correlation_id',p_key::text)); v_actor:=public.current_actor_id(); v_payload:=jsonb_build_object('calculo_id',p_calculo_id,'decisao',upper(p_decisao),'justificativa',btrim(p_justificativa)); perform public.prc_lock_idempotency_key(p_key); v_existing:=public.prc_idempotent_result(p_key,'calculation_review',v_payload); if v_existing is not null then return v_existing; end if;
  select * into v_calc from public.prc_calculos where id=p_calculo_id; if not found then raise exception 'calculo inexistente'; end if; select * into v_s from public.prc_cenarios where id=v_calc.cenario_id; if v_actor=v_calc.created_by or v_actor=v_s.created_by then raise exception 'criador do cenario ou calculo nao pode aprovar o proprio calculo'; end if; if upper(p_decisao) not in ('APPROVED','REJECTED') or length(btrim(coalesce(p_justificativa,'')))<10 then raise exception 'decisao de calculo invalida'; end if;
  insert into public.prc_calculo_decisoes(calculo_id,decisao,justificativa,actor_id) values(p_calculo_id,upper(p_decisao),btrim(p_justificativa),v_actor) returning id into v_id; insert into public.prc_requisicoes values(p_key,'calculation_review',v_actor,public.prc_sha256(v_payload),v_id,clock_timestamp()); perform public.log_audited_rpc_change('precificacao','prc_calculo_decisoes',v_id::text,'precificacao.calculo_revisado','precificacao.calculation.review',v_ctx,null,jsonb_build_object('decisao',upper(p_decisao)),jsonb_build_object('calculo_id',p_calculo_id,'justificativa',btrim(p_justificativa)),'database_rpc'); return v_id;
end $$;

revoke all on function public.prc_lock_idempotency_key(uuid) from public,anon,authenticated;
revoke all on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) from public,anon;
revoke all on function public.decidir_prc_politica_versao_idempotente(uuid,bigint,text,text) from public,anon;
revoke all on function public.criar_prc_cenario_idempotente(uuid,bigint,bigint,text,text,jsonb) from public,anon;
revoke all on function public.calcular_prc_cenario_idempotente(uuid,bigint,text) from public,anon;
revoke all on function public.decidir_prc_calculo_idempotente(uuid,bigint,text,text) from public,anon;
grant execute on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) to authenticated;
grant execute on function public.decidir_prc_politica_versao_idempotente(uuid,bigint,text,text) to authenticated;
grant execute on function public.criar_prc_cenario_idempotente(uuid,bigint,bigint,text,text,jsonb) to authenticated;
grant execute on function public.calcular_prc_cenario_idempotente(uuid,bigint,text) to authenticated;
grant execute on function public.decidir_prc_calculo_idempotente(uuid,bigint,text,text) to authenticated;
comment on function public.prc_lock_idempotency_key(uuid) is 'Private transaction lock for PRC idempotency keys.';
comment on function public.calcular_prc_cenario_idempotente(uuid,bigint,text) is 'PRC-01 calculation v2: result_sha256 covers the complete immutable snapshot, components and 18 terms.';
