-- PRC-UX-02: policy identity is generated by the governed PRC boundary.

create sequence if not exists public.prc_politica_codigo_seq;

do $$
declare
  v_next bigint;
begin
  select coalesce(max(substring(codigo from '^POL-([0-9]+)$')::bigint), 0) + 1
    into v_next
    from public.prc_politicas
   where codigo ~ '^POL-[0-9]+$';
  perform setval('public.prc_politica_codigo_seq', greatest(v_next, 1), false);
end $$;

revoke all on sequence public.prc_politica_codigo_seq from public, anon, authenticated;
revoke all on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) from public, anon, authenticated;
drop function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text);

create function public.salvar_prc_politica_versao_idempotente(
  p_key uuid,
  p_politica_id bigint,
  p_nome text,
  p_metodo text,
  p_lucro_minimo numeric,
  p_markup numeric,
  p_juros_mensais numeric,
  p_motivo text
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_payload jsonb;
  v_existing bigint;
  v_policy public.prc_politicas%rowtype;
  v_version integer;
  v_doc jsonb;
  v_id bigint;
  v_codigo text;
begin
  v_ctx := public.begin_audited_rpc(
    'precificacao.policy.manage',
    'precificacao',
    'prc_politica_versoes',
    'change_type',
    jsonb_build_object('correlation_id', p_key::text)
  );
  v_actor := public.current_actor_id();
  v_payload := jsonb_build_object(
    'politica_id', p_politica_id,
    'nome', case when p_politica_id is null then btrim(p_nome) else null end,
    'metodo', p_metodo,
    'lucro_minimo', p_lucro_minimo,
    'markup', p_markup,
    'juros_mensais', p_juros_mensais,
    'motivo', btrim(p_motivo)
  );

  perform public.prc_lock_idempotency_key(p_key);
  v_existing := public.prc_idempotent_result(p_key, 'policy', v_payload);
  if v_existing is not null then
    return v_existing;
  end if;

  if p_metodo not in ('margem_liquida', 'markup')
     or p_juros_mensais is null
     or p_juros_mensais < 0
     or length(btrim(coalesce(p_motivo, ''))) < 10 then
    raise exception 'politica invalida';
  end if;

  if p_politica_id is null then
    if length(btrim(coalesce(p_nome, ''))) = 0 then
      raise exception 'nome da nova politica e obrigatorio';
    end if;
    v_codigo := format('POL-%s', lpad(nextval('public.prc_politica_codigo_seq')::text, 8, '0'));
    insert into public.prc_politicas(codigo, nome, created_by)
    values(v_codigo, btrim(p_nome), v_actor)
    returning * into v_policy;
  else
    if nullif(btrim(coalesce(p_nome, '')), '') is not null then
      raise exception 'nome de politica existente e definido pelo sistema';
    end if;
    select * into v_policy
      from public.prc_politicas
     where id = p_politica_id;
    if not found then
      raise exception 'politica inexistente';
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('prc-policy:' || v_policy.id::text, 0));
  select coalesce(max(versao), 0) + 1
    into v_version
    from public.prc_politica_versoes
   where politica_id = v_policy.id;

  v_doc := jsonb_build_object(
    'schema', 'prc-policy-v1',
    'politica_id', v_policy.id,
    'codigo', v_policy.codigo,
    'nome', v_policy.nome,
    'versao', v_version,
    'metodo', p_metodo,
    'lucro_minimo', p_lucro_minimo,
    'markup', p_markup,
    'juros_mensais', p_juros_mensais,
    'arredondamento', 'HALF_UP',
    'casas_decimais', 2
  );

  insert into public.prc_politica_versoes(
    politica_id, versao, metodo, lucro_minimo, markup, juros_mensais,
    documento_json, documento_sha256, motivo, created_by
  ) values (
    v_policy.id, v_version, p_metodo, p_lucro_minimo, p_markup, p_juros_mensais,
    v_doc, public.prc_sha256(v_doc), btrim(p_motivo), v_actor
  ) returning id into v_id;

  insert into public.prc_requisicoes
  values(p_key, 'policy', v_actor, public.prc_sha256(v_payload), v_id, clock_timestamp());
  perform public.log_audited_rpc_change(
    'precificacao',
    'prc_politica_versoes',
    v_id::text,
    'precificacao.politica_versao_criada',
    'precificacao.policy.manage',
    v_ctx,
    null,
    v_doc,
    jsonb_build_object('motivo', btrim(p_motivo)),
    'database_rpc'
  );
  return v_id;
end $$;

revoke all on function public.salvar_prc_politica_versao_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) from public, anon, authenticated;
grant execute on function public.salvar_prc_politica_versao_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) to authenticated;
comment on function public.salvar_prc_politica_versao_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) is 'Governed PRC policy creation/versioning. Policy codes are issued atomically by the database.';
