-- PRC-UX-02: policy identity is generated by the governed PRC boundary.
-- Keep the N-1 signature during rollout. The new application calls v2 only.

create sequence if not exists public.prc_politica_codigo_seq
  minvalue 1
  maxvalue 99999999
  increment by 1
  no cycle;

do $$
declare
  v_sequence_last bigint;
  v_sequence_called boolean;
  v_sequence_next bigint;
  v_existing_next bigint;
  v_next bigint;
  v_minimum bigint;
  v_maximum bigint;
  v_increment bigint;
  v_cycles boolean;
begin
  select seqmin, seqmax, seqincrement, seqcycle
    into v_minimum, v_maximum, v_increment, v_cycles
    from pg_sequence
   where seqrelid = 'public.prc_politica_codigo_seq'::regclass;

  if v_minimum <> 1 or v_maximum <> 99999999 or v_increment <> 1 or v_cycles then
    raise exception 'prc_politica_codigo_seq possui configuracao incompativel';
  end if;

  select last_value, is_called
    into v_sequence_last, v_sequence_called
    from public.prc_politica_codigo_seq;
  v_sequence_next := case when v_sequence_called then v_sequence_last + 1 else v_sequence_last end;

  select coalesce(max(substring(codigo from '^POL-([0-9]{8})$')::bigint), 0) + 1
    into v_existing_next
    from public.prc_politicas
   where codigo ~ '^POL-[0-9]{8}$';

  v_next := greatest(v_sequence_next, v_existing_next, 1);
  if v_next > 99999999 then
    raise exception 'codigo de politica esgotado';
  end if;

  perform setval('public.prc_politica_codigo_seq', v_next, false);
end $$;

revoke all on sequence public.prc_politica_codigo_seq from public, anon, authenticated;

create or replace function public.salvar_prc_politica_versao_v2_idempotente(
  p_key uuid,
  p_politica_id bigint,
  p_nome text,
  p_metodo text,
  p_lucro_minimo numeric,
  p_markup numeric,
  p_juros_mensais numeric,
  p_motivo text
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_payload jsonb;
  v_existing bigint;
  v_policy public.prc_politicas%rowtype;
  v_version integer;
  v_doc jsonb;
  v_id bigint;
  v_codigo text;
  v_codigo_num bigint;
begin
  v_ctx := public.begin_audited_rpc(
    'precificacao.policy.manage',
    'precificacao',
    'prc_politica_versoes',
    'change_type',
    jsonb_build_object('correlation_id', p_key::text)
  );
  v_actor := public.current_actor_id();
  v_payload := jsonb_build_object(
    'politica_id', p_politica_id,
    'nome', case when p_politica_id is null then btrim(p_nome) else null end,
    'metodo', p_metodo,
    'lucro_minimo', p_lucro_minimo,
    'markup', p_markup,
    'juros_mensais', p_juros_mensais,
    'motivo', btrim(p_motivo)
  );

  perform public.prc_lock_idempotency_key(p_key);
  v_existing := public.prc_idempotent_result(p_key, 'policy', v_payload);
  if v_existing is not null then
    return v_existing;
  end if;

  if p_metodo not in ('margem_liquida', 'markup')
     or p_juros_mensais is null
     or p_juros_mensais < 0
     or length(btrim(coalesce(p_motivo, ''))) < 10 then
    raise exception 'politica invalida';
  end if;

  if p_politica_id is null then
    if length(btrim(coalesce(p_nome, ''))) not between 3 and 120 then
      raise exception 'nome da nova politica deve ter entre 3 e 120 caracteres';
    end if;
    begin
      v_codigo_num := nextval('public.prc_politica_codigo_seq');
    exception when sqlstate '2200H' then
      raise exception 'codigo de politica esgotado';
    end;
    if v_codigo_num < 1 or v_codigo_num > 99999999 then
      raise exception 'codigo de politica esgotado';
    end if;
    v_codigo := format('POL-%s', lpad(v_codigo_num::text, 8, '0'));
    insert into public.prc_politicas(codigo, nome, created_by)
    values(v_codigo, btrim(p_nome), v_actor)
    returning * into v_policy;
  else
    if nullif(btrim(coalesce(p_nome, '')), '') is not null then
      raise exception 'nome de politica existente e definido pelo sistema';
    end if;
    select * into v_policy
      from public.prc_politicas
     where id = p_politica_id;
    if not found then
      raise exception 'politica inexistente';
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('prc-policy:' || v_policy.id::text, 0));
  select coalesce(max(versao), 0) + 1
    into v_version
    from public.prc_politica_versoes
   where politica_id = v_policy.id;

  v_doc := jsonb_build_object(
    'schema', 'prc-policy-v1',
    'politica_id', v_policy.id,
    'codigo', v_policy.codigo,
    'nome', v_policy.nome,
    'versao', v_version,
    'metodo', p_metodo,
    'lucro_minimo', p_lucro_minimo,
    'markup', p_markup,
    'juros_mensais', p_juros_mensais,
    'arredondamento', 'HALF_UP',
    'casas_decimais', 2
  );

  insert into public.prc_politica_versoes(
    politica_id, versao, metodo, lucro_minimo, markup, juros_mensais,
    documento_json, documento_sha256, motivo, created_by
  ) values (
    v_policy.id, v_version, p_metodo, p_lucro_minimo, p_markup, p_juros_mensais,
    v_doc, public.prc_sha256(v_doc), btrim(p_motivo), v_actor
  ) returning id into v_id;

  insert into public.prc_requisicoes
  values(p_key, 'policy', v_actor, public.prc_sha256(v_payload), v_id, clock_timestamp());
  perform public.log_audited_rpc_change(
    'precificacao',
    'prc_politica_versoes',
    v_id::text,
    'precificacao.politica_versao_criada',
    'precificacao.policy.manage',
    v_ctx,
    null,
    v_doc,
    jsonb_build_object('motivo', btrim(p_motivo)),
    'database_rpc'
  );
  return v_id;
end $$;

-- Compatibility entrypoint for N-1 callers. $2 is intentionally ignored:
-- only v2 may issue the policy code and define policy identity.
create or replace function public.salvar_prc_politica_versao_idempotente(
  p_key uuid,
  p_codigo text,
  p_nome text,
  p_metodo text,
  p_lucro_minimo numeric,
  p_markup numeric,
  p_juros_mensais numeric,
  p_motivo text
)
returns bigint
language sql
security invoker
set search_path=public
as $$
  select public.salvar_prc_politica_versao_v2_idempotente($1, null::bigint, $3, $4, $5, $6, $7, $8)
$$;

revoke all on function public.salvar_prc_politica_versao_v2_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) from public, anon, authenticated;
grant execute on function public.salvar_prc_politica_versao_v2_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) to authenticated;
revoke all on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) from public, anon, authenticated;
grant execute on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) to authenticated;
comment on function public.salvar_prc_politica_versao_v2_idempotente(uuid,bigint,text,text,numeric,numeric,numeric,text) is 'Governed PRC policy creation/versioning. Policy codes are issued atomically by the database.';
comment on function public.salvar_prc_politica_versao_idempotente(uuid,text,text,text,numeric,numeric,numeric,text) is 'N-1 compatibility wrapper. Client supplied policy codes are ignored.';
